---
- name: set the path to config.txt on non-Ubuntu systems
  set_fact:
    config_txt_path: /boot/config.txt
  when: ansible_distribution != 'Ubuntu'

- name: set the path to config.txt for Ubuntu
  set_fact:
    config_txt_path: /boot/firmware/config.txt
  when: ansible_distribution == 'Ubuntu'

- name: check for a boot config file
  stat:
    path: "{{ config_txt_path }}"
  register: boot_config_stat

- name: enable dwc2 driver in boot config
  lineinfile:
    path: "{{ config_txt_path }}"
    create: no
    line: dtoverlay=dwc2
  when: boot_config_stat.stat.exists

- name: check for an /etc/modules file
  stat:
    path: /etc/modules
  register: etc_modules_stat

- name: enable dwc2 driver in modules
  lineinfile:
    path: /etc/modules
    create: no
    line: dwc2
  when: etc_modules_stat.stat.exists

- name: create TinyPilot privileged folder
  file:
    path: "{{ tinypilot_privileged_dir }}"
    state: directory
    owner: "root"
    group: "root"

- name: copy usb-gadget initializer
  copy:
    src: init-usb-gadget
    dest: "{{ tinypilot_privileged_dir }}/init-usb-gadget"
    owner: root
    group: root
    mode: '0700'

- name: copy usb-gadget de-initializer
  copy:
    src: remove-usb-gadget
    dest: "{{ tinypilot_privileged_dir }}/remove-usb-gadget"
    owner: root
    group: root
    mode: '0700'

- name: install usb-gadget initializer as a service
  template:
    src: usb-gadget.systemd.j2
    dest: /lib/systemd/system/usb-gadget.service
    owner: root
    group: root
    mode: '0644'
  register: usb_gadget_template

- name: patch HID module
  get_url:
    url: https://storage.googleapis.com/jason-tinypilotkvm/usb_f_hid.ko
    dest: /lib/modules/{{ ansible_kernel }}/kernel/drivers/usb/gadget/function/usb_f_hid.ko
    mode: '0664'
  when: ansible_kernel is version('5.15', '<') and ansible_kernel is version('5.10', '>=')

- name: patch usb-gadget initializer
  ansible.builtin.lineinfile:
    path: "{{ tinypilot_privileged_dir }}/init-usb-gadget"
    line: 'echo 1 > "${KEYBOARD_FUNCTIONS_DIR}/no_out_endpoint"'
    # Either replace the line this regex is found on.
    regex: ^{{ 'echo 1 > "${KEYBOARD_FUNCTIONS_DIR}/no_out_endpoint"' | regex_escape() }}
    # Or insert the line after this regex is found.
    insertafter: ^{{ 'mkdir -p "$KEYBOARD_FUNCTIONS_DIR"' | regex_escape() }}$
    # Otherwise add the line to the EOF.
  when: ansible_kernel is version('5.15', '<') and ansible_kernel is version('5.10', '>=')

- name: enable systemd usb-gadget initializer service file
  systemd:
    name: usb-gadget
    enabled: yes
    daemon_reload: "{{ usb_gadget_template.changed }}"
