
# Installing TinyPilot via git is deprecated and no longer used for production
# installs, but we still rely on it for testing the Ansible role.

- name: collect TinyPilot required apt packages on all systems
  set_fact:
    tinypilot_packages:
      - git
      - python3-venv
      - sudo
    can_install_pip3: >-
      {{ (ansible_distribution == 'Debian' and ansible_distribution_version is version('11', '>='))
         or (ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('20.04', '>=')) }}

- name: add pip to required apt packages
  set_fact:
    tinypilot_packages: "{{ tinypilot_packages }} + ['python-pip']"
  when: not can_install_pip3

- name: add pip3 to required apt packages
  set_fact:
    tinypilot_packages: "{{ tinypilot_packages }} + ['python3-pip']"
  when: can_install_pip3

- name: install TinyPilot pre-requisite packages
  apt:
    name: "{{ tinypilot_packages }}"
    state: present

- name: create TinyPilot folder
  file:
    path: "{{ tinypilot_dir }}"
    state: directory
    owner: "{{ tinypilot_user }}"
    group: "{{ tinypilot_group }}"

- name: suppress warnings about git ownership for TinyPilot directory
  git_config:
    scope: global
    name: safe.directory
    value: "{{ tinypilot_dir }}"

- name: '[DEPRECATED] get TinyPilot repo'
  git:
    repo: "{{ tinypilot_repo }}"
    dest: "{{ tinypilot_dir }}"
    version: "{{ tinypilot_repo_branch }}"
    accept_hostkey: yes
  notify:
    - restart TinyPilot service
