---
- name: enable dwc2 driver in boot config
  lineinfile:
    path: /boot/config.txt
    create: no
    line: dtoverlay=dwc2

- name: enable dwc2 driver in modules
  lineinfile:
    path: /etc/modules
    create: no
    line: dwc2

- name: install usb-gadget initializer as a service
  template:
    src: usb-gadget.systemd.j2
    dest: /lib/systemd/system/usb-gadget.service
    owner: root
    group: root
    mode: '0644'

- name: enable systemd usb-gadget initializer service file
  systemd:
    name: usb-gadget
    enabled: yes