---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian10
    image: geerlingguy/docker-debian10-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: debian11
    image: geerlingguy/docker-debian11-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  inventory:
    hosts:
      all:
        vars:
          ansible_user: root
          ustreamer_overrides:
            ustreamer_interface: '127.0.0.1'
            ustreamer_port: 8001
            ustreamer_repo: https://github.com/tiny-pilot/ustreamer.git
            ustreamer_h264_sink: null
            ustreamer_h264_sink_mode: null
            ustreamer_h264_sink_rm: null
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - destroy
