#!/bin/bash
#
# Presents a backing file as device to the USB host.

# Exit on unset variable.
set -u

# Exit on first error.
set -e

readonly USB_GADGET_PATH="/sys/kernel/config/usb_gadget/g1"
readonly MASS_STORAGE_FUNCTIONS_DIR="${USB_GADGET_PATH}/functions/mass_storage.0"

print_help() {
  cat << EOF
Usage: ${0##*/} [-h] backing_file
  Presents a backing file as device to the USB host.
  -h Display this help and exit.
EOF
}

# Parse command-line arguments.
while getopts 'h' opt; do
  case "${opt}" in
    h)
      print_help
      exit
      ;;
    *)
      print_help >&2
      exit 1
  esac
done

# Ensure 'backing_file' is given and it exists.
shift $((OPTIND - 1))
if (( $# == 0 )); then
  echo 'Input parameter missing: backing_file' >&2
  exit 1
fi
readonly BACKING_FILE="$1"
if [[ ! -f "${BACKING_FILE}" ]]; then
  echo "No such file: ${BACKING_FILE}" >&2
  exit 1
fi

# Set backing file.
echo "${BACKING_FILE}" > "${MASS_STORAGE_FUNCTIONS_DIR}/lun.0/file"
