#!/bin/bash

# Reads the tinypilot-updater systemd log and cuts out the junk content.

# Exit on first error.
set -e

# Treat undefined environment variables as errors.
set -u

sudo journalctl -u tinypilot-updater \
  | grep tinypilot-update-svc \
  | sed -E 's/^.*tinypilot-update-svc\[[0-9]+\]: //g'
