#!/usr/bin/env bash

# Tears down USB gadgets per: https://www.kernel.org/doc/Documentation/usb/gadget_configfs.txt

DEVICE=g1
STRINGS=strings/0x409
FUNCTIONS=functions/*

# Exit on first error.
set -e

# Echo commands to stdout.
set -x

# Treat undefined environment variables as errors.
set -u

cd /sys/kernel/config/usb_gadget/

if [ ! -d $DEVICE ]; then
    echo "Gadget does not exist, quitting."
    exit 0
fi

pushd $DEVICE

# disable all
if [ -n "$(cat UDC)" ]; then
echo "" > UDC
fi

# walk items in `configs`
for config in configs/* ; do
    # short-circuit if there are no entries
    [ $config == 'configs/*' ] && break

    # remove all functions from configs.
    for func in $FUNCTIONS ; do
        file=$config/$(basename $func)
        [ -e $file ] && rm $file
    done

    # remove strings in config
    [ -d $config/$STRINGS ] && rmdir $config/$STRINGS
    # remove config
    rmdir $config
done

# remove functions
for func in $FUNCTIONS ; do
    [ -d $func ] && rmdir $func
done

# remove strings from device
[ -d $STRINGS ] && rmdir $STRINGS

popd
# remove the device
rmdir $DEVICE
